
name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  fl_chart: ^0.66.2
  percent_indicator: ^4.2.5
  google_mobile_ads: ^7.0.0
  countup: ^0.1.4
  intl: ^0.19.0
  provider: ^6.1.5+1
  go_router: ^17.1.0
  collection: ^1.19.1
  image_picker: ^1.2.1
  pedometer: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
